In [2]:
## this example adapted from a linear regression example at:
## https://www.geeksforgeeks.org/linear-regression-using-pytorch/

In [28]:
import torch
from torch.autograd import Variable
from scipy.spatial import distance as dist

In [4]:
x_data = Variable(torch.Tensor([[0.0, 0.0], [1.0, 0.0], [2.0, 0.0]])) ## "trace"
y_data = Variable(torch.Tensor([[0.0, 1.0], [1.0, 1.0], [2.0, 1.0]])) ## "reference"

In [5]:
x_data

tensor([[0., 0.],
        [1., 0.],
        [2., 0.]])

In [6]:
y_data

tensor([[0., 1.],
        [1., 1.],
        [2., 1.]])

In [110]:
class LinearTransform(torch.nn.Module):
 
    def __init__(self):
        super(LinearTransform, self).__init__()
        self.transform = torch.nn.Linear(2, 2, bias=True)  # two in and two out
 
    def forward(self, x):
        y_pred = self.transform(x)
        return y_pred


def custom_loss(tra_verts, ref_verts):
    print tra_verts
    print ref_verts
    sum_dist = torch.tensor(0.0)
    for i, v in enumerate(tra_verts):
        rv = ref_verts[i]
        current_dist = ((v[0] - rv[0]) ** 2 + (v[1] - rv[1]) ** 2) 
        sum_dist.add_(current_dist)
    print sum_dist
        
    return torch.tensor(sum_dist, requires_grad=True)

In [111]:
# our model
model = LinearTransform()

In [112]:
# define a loss and optimizer

## loss
## TODO: this should perhaps be a different, to take into account the 
## "cost" of the transformation as measured by: (1) the "area swept out by the stroke
## upon being moved into place plus (2) the "residual_area" between the trace and reference
# criterion = torch.nn.MSELoss(size_average=True) 

## optimizier
optimizer = torch.optim.SGD(model.parameters(), lr = 0.01)

In [113]:
num_train_steps = 5000
for i,epoch in enumerate(range(num_train_steps)):
 
    # Forward pass: Compute predicted y by passing 
    # x to the model
    pred_y = model(x_data)
 
    # Compute and print loss
    loss = custom_loss(pred_y, y_data)
    
    # Zero gradients, perform a backward pass, 
    # and update the weights.
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    
    if i%1000==0:
        print('epoch {}, loss {}'.format(epoch, loss.data[0]))


tensor([[0.0275, 0.5080],
        [0.0677, 1.0569],
        [0.1079, 1.6058]], grad_fn=<ThAddmmBackward>)
tensor([[-1.,  0.],
        [ 1.,  0.],
        [ 3.,  0.]])
tensor(14.2428, grad_fn=<ThAddBackward>)
epoch 0, loss 14.2427711487
tensor([[0.0834, 0.4446],
        [0.2580, 0.9081],
        [0.4325, 1.3717]], grad_fn=<ThAddmmBackward>)
tensor([[-1.,  0.],
        [ 1.,  0.],
        [ 3.,  0.]])
tensor(11.2201, grad_fn=<ThAddBackward>)
tensor([[0.1279, 0.3901],
        [0.4200, 0.7806],
        [0.7121, 1.1711]], grad_fn=<ThAddmmBackward>)
tensor([[-1.,  0.],
        [ 1.,  0.],
        [ 3.,  0.]])
tensor(8.9760, grad_fn=<ThAddBackward>)
tensor([[0.1627, 0.3433],
        [0.5579, 0.6713],
        [0.9532, 0.9994]], grad_fn=<ThAddmmBackward>)
tensor([[-1.,  0.],
        [ 1.,  0.],
        [ 3.,  0.]])
tensor(7.3042, grad_fn=<ThAddBackward>)
tensor([[0.1892, 0.3030],
        [0.6752, 0.5776],
        [1.1611, 0.8523]], grad_fn=<ThAddmmBackward>)
tensor([[-1.,  0.],
        [ 1.,  0

/Users/zixianchai/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:18: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number


tensor(0.0407, grad_fn=<ThAddBackward>)
tensor([[-0.8244,  0.0081],
        [ 1.0490,  0.0023],
        [ 2.9225, -0.0036]], grad_fn=<ThAddmmBackward>)
tensor([[-1.,  0.],
        [ 1.,  0.],
        [ 3.,  0.]])
tensor(0.0393, grad_fn=<ThAddBackward>)
tensor([[-0.8274,  0.0080],
        [ 1.0482,  0.0022],
        [ 2.9238, -0.0035]], grad_fn=<ThAddmmBackward>)
tensor([[-1.,  0.],
        [ 1.,  0.],
        [ 3.,  0.]])
tensor(0.0380, grad_fn=<ThAddBackward>)
tensor([[-0.8303,  0.0078],
        [ 1.0474,  0.0022],
        [ 2.9251, -0.0035]], grad_fn=<ThAddmmBackward>)
tensor([[-1.,  0.],
        [ 1.,  0.],
        [ 3.,  0.]])
tensor(0.0367, grad_fn=<ThAddBackward>)
tensor([[-0.8331,  0.0077],
        [ 1.0466,  0.0021],
        [ 2.9263, -0.0034]], grad_fn=<ThAddmmBackward>)
tensor([[-1.,  0.],
        [ 1.,  0.],
        [ 3.,  0.]])
tensor(0.0355, grad_fn=<ThAddBackward>)
tensor([[-0.8359,  0.0076],
        [ 1.0458,  0.0021],
        [ 2.9276, -0.0033]], grad_fn=<ThAddmmBackwar

tensor(0.0002, grad_fn=<ThAddBackward>)
tensor([[-0.9876,  0.0006],
        [ 1.0035,  0.0002],
        [ 2.9945, -0.0003]], grad_fn=<ThAddmmBackward>)
tensor([[-1.,  0.],
        [ 1.,  0.],
        [ 3.,  0.]])
tensor(0.0002, grad_fn=<ThAddBackward>)
tensor([[-0.9878,  0.0006],
        [ 1.0034,  0.0002],
        [ 2.9946, -0.0002]], grad_fn=<ThAddmmBackward>)
tensor([[-1.,  0.],
        [ 1.,  0.],
        [ 3.,  0.]])
tensor(0.0002, grad_fn=<ThAddBackward>)
tensor([[-0.9880,  0.0006],
        [ 1.0033,  0.0002],
        [ 2.9947, -0.0002]], grad_fn=<ThAddmmBackward>)
tensor([[-1.,  0.],
        [ 1.,  0.],
        [ 3.,  0.]])
tensor(0.0002, grad_fn=<ThAddBackward>)
tensor([[-0.9882,  0.0005],
        [ 1.0033,  0.0002],
        [ 2.9948, -0.0002]], grad_fn=<ThAddmmBackward>)
tensor([[-1.,  0.],
        [ 1.,  0.],
        [ 3.,  0.]])
tensor(0.0002, grad_fn=<ThAddBackward>)
tensor([[-0.9884,  0.0005],
        [ 1.0032,  0.0001],
        [ 2.9949, -0.0002]], grad_fn=<ThAddmmBackwar

tensor([[-9.9820e-01,  8.3008e-05],
        [ 1.0005e+00,  2.3179e-05],
        [ 2.9992e+00, -3.6650e-05]], grad_fn=<ThAddmmBackward>)
tensor([[-1.,  0.],
        [ 1.,  0.],
        [ 3.,  0.]])
tensor(4.1438e-06, grad_fn=<ThAddBackward>)
tensor([[-9.9823e-01,  8.1617e-05],
        [ 1.0005e+00,  2.2791e-05],
        [ 2.9992e+00, -3.6036e-05]], grad_fn=<ThAddmmBackward>)
tensor([[-1.,  0.],
        [ 1.,  0.],
        [ 3.,  0.]])
tensor(4.0057e-06, grad_fn=<ThAddBackward>)
tensor([[-9.9826e-01,  8.0250e-05],
        [ 1.0005e+00,  2.2409e-05],
        [ 2.9992e+00, -3.5432e-05]], grad_fn=<ThAddmmBackward>)
tensor([[-1.,  0.],
        [ 1.,  0.],
        [ 3.,  0.]])
tensor(3.8730e-06, grad_fn=<ThAddBackward>)
tensor([[-9.9829e-01,  7.8905e-05],
        [ 1.0005e+00,  2.2034e-05],
        [ 2.9992e+00, -3.4838e-05]], grad_fn=<ThAddmmBackward>)
tensor([[-1.,  0.],
        [ 1.,  0.],
        [ 3.,  0.]])
tensor(3.7439e-06, grad_fn=<ThAddBackward>)
tensor([[-9.9832e-01,  7.7583e-05],


tensor([[-1.,  0.],
        [ 1.,  0.],
        [ 3.,  0.]])
tensor(1.7275e-07, grad_fn=<ThAddBackward>)
tensor([[-9.9964e-01,  1.6673e-05],
        [ 1.0001e+00,  4.6557e-06],
        [ 2.9998e+00, -7.3614e-06]], grad_fn=<ThAddmmBackward>)
tensor([[-1.,  0.],
        [ 1.,  0.],
        [ 3.,  0.]])
tensor(1.6708e-07, grad_fn=<ThAddBackward>)
tensor([[-9.9964e-01,  1.6394e-05],
        [ 1.0001e+00,  4.5777e-06],
        [ 2.9998e+00, -7.2380e-06]], grad_fn=<ThAddmmBackward>)
tensor([[-1.,  0.],
        [ 1.,  0.],
        [ 3.,  0.]])
tensor(1.6146e-07, grad_fn=<ThAddBackward>)
tensor([[-9.9965e-01,  1.6119e-05],
        [ 1.0001e+00,  4.5010e-06],
        [ 2.9998e+00, -7.1168e-06]], grad_fn=<ThAddmmBackward>)
tensor([[-1.,  0.],
        [ 1.,  0.],
        [ 3.,  0.]])
tensor(1.5617e-07, grad_fn=<ThAddBackward>)
tensor([[-9.9966e-01,  1.5849e-05],
        [ 1.0001e+00,  4.4256e-06],
        [ 2.9998e+00, -6.9975e-06]], grad_fn=<ThAddmmBackward>)
tensor([[-1.,  0.],
        [ 1.,  0

tensor([[-9.9998e-01,  1.0980e-06],
        [ 1.0000e+00,  3.0660e-07],
        [ 3.0000e+00, -4.8477e-07]], grad_fn=<ThAddmmBackward>)
tensor([[-1.,  0.],
        [ 1.,  0.],
        [ 3.,  0.]])
tensor(7.4107e-10, grad_fn=<ThAddBackward>)
tensor([[-9.9998e-01,  1.0796e-06],
        [ 1.0000e+00,  3.0146e-07],
        [ 3.0000e+00, -4.7665e-07]], grad_fn=<ThAddmmBackward>)
tensor([[-1.,  0.],
        [ 1.,  0.],
        [ 3.,  0.]])
tensor(7.1797e-10, grad_fn=<ThAddBackward>)
tensor([[-9.9998e-01,  1.0615e-06],
        [ 1.0000e+00,  2.9641e-07],
        [ 3.0000e+00, -4.6867e-07]], grad_fn=<ThAddmmBackward>)
tensor([[-1.,  0.],
        [ 1.,  0.],
        [ 3.,  0.]])
tensor(6.9112e-10, grad_fn=<ThAddBackward>)
tensor([[-9.9998e-01,  1.0437e-06],
        [ 1.0000e+00,  2.9144e-07],
        [ 3.0000e+00, -4.6081e-07]], grad_fn=<ThAddmmBackward>)
tensor([[-1.,  0.],
        [ 1.,  0.],
        [ 3.,  0.]])
tensor(6.7028e-10, grad_fn=<ThAddBackward>)
tensor([[-9.9998e-01,  1.0262e-06],


tensor([[-1.0000e+00,  1.1219e-07],
        [ 1.0000e+00,  3.1328e-08],
        [ 3.0000e+00, -4.9535e-08]], grad_fn=<ThAddmmBackward>)
tensor([[-1.,  0.],
        [ 1.,  0.],
        [ 3.,  0.]])
tensor(1.1399e-11, grad_fn=<ThAddBackward>)
tensor([[-1.0000e+00,  1.1031e-07],
        [ 1.0000e+00,  3.0803e-08],
        [ 3.0000e+00, -4.8705e-08]], grad_fn=<ThAddmmBackward>)
tensor([[-1.,  0.],
        [ 1.,  0.],
        [ 3.,  0.]])
tensor(9.9347e-12, grad_fn=<ThAddBackward>)
tensor([[-1.0000e+00,  1.0846e-07],
        [ 1.0000e+00,  3.0287e-08],
        [ 3.0000e+00, -4.7889e-08]], grad_fn=<ThAddmmBackward>)
tensor([[-1.,  0.],
        [ 1.,  0.],
        [ 3.,  0.]])
tensor(1.0222e-11, grad_fn=<ThAddBackward>)
tensor([[-1.0000e+00,  1.0665e-07],
        [ 1.0000e+00,  2.9780e-08],
        [ 3.0000e+00, -4.7086e-08]], grad_fn=<ThAddmmBackward>)
tensor([[-1.,  0.],
        [ 1.,  0.],
        [ 3.,  0.]])
tensor(1.0221e-11, grad_fn=<ThAddBackward>)
tensor([[-1.0000e+00,  1.0486e-07],


tensor(1.0207e-11, grad_fn=<ThAddBackward>)
tensor([[-1.0000e+00,  1.8399e-08],
        [ 1.0000e+00,  5.1377e-09],
        [ 3.0000e+00, -8.1235e-09]], grad_fn=<ThAddmmBackward>)
tensor([[-1.,  0.],
        [ 1.,  0.],
        [ 3.,  0.]])
tensor(1.0207e-11, grad_fn=<ThAddBackward>)
tensor([[-1.0000e+00,  1.8091e-08],
        [ 1.0000e+00,  5.0516e-09],
        [ 3.0000e+00, -7.9874e-09]], grad_fn=<ThAddmmBackward>)
tensor([[-1.,  0.],
        [ 1.,  0.],
        [ 3.,  0.]])
tensor(1.0207e-11, grad_fn=<ThAddBackward>)
tensor([[-1.0000e+00,  1.7788e-08],
        [ 1.0000e+00,  4.9670e-09],
        [ 3.0000e+00, -7.8535e-09]], grad_fn=<ThAddmmBackward>)
tensor([[-1.,  0.],
        [ 1.,  0.],
        [ 3.,  0.]])
tensor(1.0207e-11, grad_fn=<ThAddBackward>)
tensor([[-1.0000e+00,  1.7490e-08],
        [ 1.0000e+00,  4.8838e-09],
        [ 3.0000e+00, -7.7220e-09]], grad_fn=<ThAddmmBackward>)
tensor([[-1.,  0.],
        [ 1.,  0.],
        [ 3.,  0.]])
tensor(1.0207e-11, grad_fn=<ThAddBac

tensor([[-1.0000e+00,  3.7585e-09],
        [ 1.0000e+00,  1.0495e-09],
        [ 3.0000e+00, -1.6595e-09]], grad_fn=<ThAddmmBackward>)
tensor([[-1.,  0.],
        [ 1.,  0.],
        [ 3.,  0.]])
tensor(1.0207e-11, grad_fn=<ThAddBackward>)
tensor([[-1.0000e+00,  3.6956e-09],
        [ 1.0000e+00,  1.0320e-09],
        [ 3.0000e+00, -1.6317e-09]], grad_fn=<ThAddmmBackward>)
tensor([[-1.,  0.],
        [ 1.,  0.],
        [ 3.,  0.]])
tensor(1.0207e-11, grad_fn=<ThAddBackward>)
tensor([[-1.0000e+00,  3.6337e-09],
        [ 1.0000e+00,  1.0147e-09],
        [ 3.0000e+00, -1.6043e-09]], grad_fn=<ThAddmmBackward>)
tensor([[-1.,  0.],
        [ 1.,  0.],
        [ 3.,  0.]])
tensor(1.0207e-11, grad_fn=<ThAddBackward>)
tensor([[-1.0000e+00,  3.5728e-09],
        [ 1.0000e+00,  9.9766e-10],
        [ 3.0000e+00, -1.5774e-09]], grad_fn=<ThAddmmBackward>)
tensor([[-1.,  0.],
        [ 1.,  0.],
        [ 3.,  0.]])
tensor(1.0207e-11, grad_fn=<ThAddBackward>)
tensor([[-1.0000e+00,  3.5129e-09],


tensor([[-1.0000e+00,  3.1891e-10],
        [ 1.0000e+00,  8.9053e-11],
        [ 3.0000e+00, -1.4081e-10]], grad_fn=<ThAddmmBackward>)
tensor([[-1.,  0.],
        [ 1.,  0.],
        [ 3.,  0.]])
tensor(1.0207e-11, grad_fn=<ThAddBackward>)
tensor([[-1.0000e+00,  3.1357e-10],
        [ 1.0000e+00,  8.7561e-11],
        [ 3.0000e+00, -1.3845e-10]], grad_fn=<ThAddmmBackward>)
tensor([[-1.,  0.],
        [ 1.,  0.],
        [ 3.,  0.]])
tensor(1.0207e-11, grad_fn=<ThAddBackward>)
tensor([[-1.0000e+00,  3.0831e-10],
        [ 1.0000e+00,  8.6094e-11],
        [ 3.0000e+00, -1.3613e-10]], grad_fn=<ThAddmmBackward>)
tensor([[-1.,  0.],
        [ 1.,  0.],
        [ 3.,  0.]])
tensor(1.0207e-11, grad_fn=<ThAddBackward>)
tensor([[-1.0000e+00,  3.0315e-10],
        [ 1.0000e+00,  8.4652e-11],
        [ 3.0000e+00, -1.3385e-10]], grad_fn=<ThAddmmBackward>)
tensor([[-1.,  0.],
        [ 1.,  0.],
        [ 3.,  0.]])
tensor(1.0207e-11, grad_fn=<ThAddBackward>)
tensor([[-1.0000e+00,  2.9807e-10],


tensor([[-1.0000e+00,  2.4867e-11],
        [ 1.0000e+00,  6.9440e-12],
        [ 3.0000e+00, -1.0979e-11]], grad_fn=<ThAddmmBackward>)
tensor([[-1.,  0.],
        [ 1.,  0.],
        [ 3.,  0.]])
tensor(1.0207e-11, grad_fn=<ThAddBackward>)
tensor([[-1.0000e+00,  2.4451e-11],
        [ 1.0000e+00,  6.8277e-12],
        [ 3.0000e+00, -1.0795e-11]], grad_fn=<ThAddmmBackward>)
tensor([[-1.,  0.],
        [ 1.,  0.],
        [ 3.,  0.]])
tensor(1.0207e-11, grad_fn=<ThAddBackward>)
tensor([[-1.0000e+00,  2.4041e-11],
        [ 1.0000e+00,  6.7133e-12],
        [ 3.0000e+00, -1.0615e-11]], grad_fn=<ThAddmmBackward>)
tensor([[-1.,  0.],
        [ 1.,  0.],
        [ 3.,  0.]])
tensor(1.0207e-11, grad_fn=<ThAddBackward>)
tensor([[-1.0000e+00,  2.3638e-11],
        [ 1.0000e+00,  6.6008e-12],
        [ 3.0000e+00, -1.0437e-11]], grad_fn=<ThAddmmBackward>)
tensor([[-1.,  0.],
        [ 1.,  0.],
        [ 3.,  0.]])
tensor(1.0207e-11, grad_fn=<ThAddBackward>)
tensor([[-1.0000e+00,  2.3242e-11],


tensor(1.0207e-11, grad_fn=<ThAddBackward>)
tensor([[-1.0000e+00,  1.8432e-12],
        [ 1.0000e+00,  5.1470e-13],
        [ 3.0000e+00, -8.1382e-13]], grad_fn=<ThAddmmBackward>)
tensor([[-1.,  0.],
        [ 1.,  0.],
        [ 3.,  0.]])
tensor(1.0207e-11, grad_fn=<ThAddBackward>)
tensor([[-1.0000e+00,  1.8123e-12],
        [ 1.0000e+00,  5.0608e-13],
        [ 3.0000e+00, -8.0018e-13]], grad_fn=<ThAddmmBackward>)
tensor([[-1.,  0.],
        [ 1.,  0.],
        [ 3.,  0.]])
tensor(1.0207e-11, grad_fn=<ThAddBackward>)
tensor([[-1.0000e+00,  1.7820e-12],
        [ 1.0000e+00,  4.9760e-13],
        [ 3.0000e+00, -7.8677e-13]], grad_fn=<ThAddmmBackward>)
tensor([[-1.,  0.],
        [ 1.,  0.],
        [ 3.,  0.]])
tensor(1.0207e-11, grad_fn=<ThAddBackward>)
tensor([[-1.0000e+00,  1.7521e-12],
        [ 1.0000e+00,  4.8926e-13],
        [ 3.0000e+00, -7.7359e-13]], grad_fn=<ThAddmmBackward>)
tensor([[-1.,  0.],
        [ 1.,  0.],
        [ 3.,  0.]])
tensor(1.0207e-11, grad_fn=<ThAddBac

tensor([[-1.0000e+00,  1.4618e-13],
        [ 1.0000e+00,  4.0818e-14],
        [ 3.0000e+00, -6.4539e-14]], grad_fn=<ThAddmmBackward>)
tensor([[-1.,  0.],
        [ 1.,  0.],
        [ 3.,  0.]])
tensor(1.0207e-11, grad_fn=<ThAddBackward>)
tensor([[-1.0000e+00,  1.4373e-13],
        [ 1.0000e+00,  4.0134e-14],
        [ 3.0000e+00, -6.3458e-14]], grad_fn=<ThAddmmBackward>)
tensor([[-1.,  0.],
        [ 1.,  0.],
        [ 3.,  0.]])
tensor(1.0207e-11, grad_fn=<ThAddBackward>)
tensor([[-1.0000e+00,  1.4132e-13],
        [ 1.0000e+00,  3.9462e-14],
        [ 3.0000e+00, -6.2395e-14]], grad_fn=<ThAddmmBackward>)
tensor([[-1.,  0.],
        [ 1.,  0.],
        [ 3.,  0.]])
tensor(1.0207e-11, grad_fn=<ThAddBackward>)
tensor([[-1.0000e+00,  1.3895e-13],
        [ 1.0000e+00,  3.8801e-14],
        [ 3.0000e+00, -6.1349e-14]], grad_fn=<ThAddmmBackward>)
tensor([[-1.,  0.],
        [ 1.,  0.],
        [ 3.,  0.]])
tensor(1.0207e-11, grad_fn=<ThAddBackward>)
tensor([[-1.0000e+00,  1.3662e-13],


KeyboardInterrupt: 

In [107]:
## this will "freeze" the weights of the model so we can apply it
model.eval()

LinearTransform(
  (transform): Linear(in_features=2, out_features=2, bias=True)
)

In [108]:
## uncomment the below to get the matrix in numpy form
weight_matrix = model.transform.weight.data.numpy()
print 'weight matrix'
print weight_matrix
print ' '
bias_matrix = model.transform.bias.data.numpy()
print 'bias matrix'
print bias_matrix

weight matrix
[[ 1.9999979e+00 -8.3251059e-02]
 [ 7.0893589e-38  4.6625262e-01]]
 
bias matrix
[-9.999973e-01 -9.835959e-38]


In [109]:
## does it handle a new point properly? (i.e., move it up by 1 unit along the y-axis?)
new_var = Variable(torch.Tensor([[3.0,0.0]]))
pred_y = model(new_var)
print("predict (after training)", model(new_var).data)

('predict (after training)', tensor([[5.0000e+00, 1.1432e-37]]))


In [14]:
# try scaling
x_data = Variable(torch.Tensor([[0.0, 0.0], [1.0, 0.0], [2.0, 0.0]])) ## "trace"
y_data = Variable(torch.Tensor([[-1.0, 0.0], [1.0, 0.0], [3.0, 0.0]])) ## "reference"

num_train_steps = 10000
for i,epoch in enumerate(range(num_train_steps)):
 
    # Forward pass: Compute predicted y by passing 
    # x to the model
    pred_y = model(x_data)
 
    # Compute and print loss
    loss = criterion(pred_y, y_data)
 
    # Zero gradients, perform a backward pass, 
    # and update the weights.
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    
    if i%1000==0:
        print('epoch {}, loss {}'.format(epoch, loss.data[0]))

/Users/zixianchai/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:22: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number


epoch 0, loss 0.83333337307
epoch 1000, loss 0.00135584396776
epoch 2000, loss 5.05024718223e-06
epoch 3000, loss 1.89469133716e-08
epoch 4000, loss 9.38770380876e-11
epoch 5000, loss 6.24332113786e-11
epoch 6000, loss 6.23675416866e-11
epoch 7000, loss 6.23672988254e-11
epoch 8000, loss 6.23672988254e-11
epoch 9000, loss 6.23672988254e-11


In [15]:
## does it handle a new point properly? (i.e., move it up by 1 unit along the y-axis?)
new_var = Variable(torch.Tensor([[3.0,0.0], [5.0, 0.0], [7.0, 0.0]]))
pred_y = model(new_var)
print("predict (after training)", model(new_var).data)

('predict (after training)', tensor([[ 5.0000, -0.0000],
        [ 9.0000, -0.0000],
        [12.9999, -0.0000]]))
